/**
 * The client script the generated manual ships, as a string.
 *
 * Everything it does is progressive: the page is complete and readable in Thai
 * before this file runs, and stays complete if it never does. That is not a
 * preference — the manual is opened from a USB stick over `file://` on a shop
 * floor, and the two features here (a language switch and a filter) are the
 * kind that quietly take a page with them when they fail.
 *
 * No dependency, no build step, no `fetch`: the catalogue text is already in the
 * document in both languages, and filtering reads pre-computed `data-search-*`
 * attributes rather than walking the DOM for text.
 */

export const MANUAL_JS = `/* Generated by scripts/generate-html-manual.mjs — do not edit. */
(function () {
  "use strict";

  var STORAGE_KEY = "industrial-sas-manual-locale";
  var LOCALES = ["th", "en"];
  var root = document.documentElement;

  function readStoredLocale() {
    try {
      var stored = window.localStorage.getItem(STORAGE_KEY);
      return LOCALES.indexOf(stored) === -1 ? null : stored;
    } catch (error) {
      // file:// origins and privacy modes may refuse storage. The switch still
      // works for the current page; it just does not follow the reader.
      return null;
    }
  }

  function storeLocale(locale) {
    try {
      window.localStorage.setItem(STORAGE_KEY, locale);
    } catch (error) {
      /* ignored on purpose — see readStoredLocale */
    }
  }

  function applyLocale(locale) {
    LOCALES.forEach(function (candidate) {
      root.classList.toggle("lang-" + candidate, candidate === locale);
    });
    root.setAttribute("lang", locale);
    root.setAttribute("data-manual-locale", locale);

    var title = root.getAttribute("data-title-" + locale);
    if (title) document.title = title;

    document.querySelectorAll("[data-set-locale]").forEach(function (button) {
      var pressed = button.getAttribute("data-set-locale") === locale;
      button.setAttribute("aria-pressed", pressed ? "true" : "false");
    });

    updateCount();
  }

  function currentLocale() {
    return root.classList.contains("lang-en") ? "en" : "th";
  }

  document.querySelectorAll("[data-set-locale]").forEach(function (button) {
    button.addEventListener("click", function () {
      var locale = button.getAttribute("data-set-locale");
      applyLocale(locale);
      storeLocale(locale);
    });
  });

  var search = document.querySelector("[data-manual-search]");
  var category = document.querySelector("[data-manual-category]");
  var cards = Array.prototype.slice.call(
    document.querySelectorAll("[data-task-id]"),
  );
  var count = document.querySelector("[data-result-count]");
  var empty = document.querySelector("[data-empty]");

  function normalise(value) {
    return (value || "").toLowerCase().trim();
  }

  function updateCount() {
    if (!count) return;
    var shown = cards.filter(function (card) {
      return !card.hidden;
    }).length;
    LOCALES.forEach(function (locale) {
      var slot = count.querySelector('[data-lang="' + locale + '"]');
      if (!slot) return;
      var template = count.getAttribute("data-template-" + locale) || "";
      slot.textContent = template
        .replace("{shown}", String(shown))
        .replace("{total}", String(cards.length));
    });
    if (empty) empty.hidden = shown !== 0;
  }

  function applyFilter() {
    var term = normalise(search && search.value);
    var group = (category && category.value) || "all";
    cards.forEach(function (card) {
      var haystack =
        normalise(card.getAttribute("data-search-th")) +
        " " +
        normalise(card.getAttribute("data-search-en"));
      var matchesTerm = term === "" || haystack.indexOf(term) !== -1;
      var matchesGroup =
        group === "all" || card.getAttribute("data-category") === group;
      card.hidden = !(matchesTerm && matchesGroup);
    });
    updateCount();
  }

  if (search) search.addEventListener("input", applyFilter);
  if (category) category.addEventListener("change", applyFilter);

  applyLocale(readStoredLocale() || currentLocale());
  applyFilter();
})();
`;
